// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClassifierEntity
 */
export interface ClassifierEntity {
    /**
     * 
     * @type {number}
     * @memberof ClassifierEntity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassifierEntity
     */
    classifierName?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassifierEntity
     */
    userId?: number;
}


