// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IntentTO } from './intent-to';

/**
 * 
 * @export
 * @interface ClassifierTO
 */
export interface ClassifierTO {
    /**
     * 
     * @type {number}
     * @memberof ClassifierTO
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof ClassifierTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassifierTO
     */
    classifierName: string;
    /**
     * 
     * @type {Array<IntentTO>}
     * @memberof ClassifierTO
     */
    intents: Array<IntentTO>;
}


