// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Issuer } from './issuer';
import { StateTO } from './state-to';

/**
 * 
 * @export
 * @interface DialogueDataTO
 */
export interface DialogueDataTO {
    /**
     * 
     * @type {number}
     * @memberof DialogueDataTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof DialogueDataTO
     */
    turn: number;
    /**
     * 
     * @type {string}
     * @memberof DialogueDataTO
     */
    transcript?: string;
    /**
     * 
     * @type {string}
     * @memberof DialogueDataTO
     */
    systemTranscript?: string;
    /**
     * 
     * @type {number}
     * @memberof DialogueDataTO
     */
    dialogueId?: number;
    /**
     * 
     * @type {StateTO}
     * @memberof DialogueDataTO
     */
    stateTO?: StateTO;
    /**
     * 
     * @type {Issuer}
     * @memberof DialogueDataTO
     */
    issuer?: Issuer;
}


