// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DialogueDataTO } from './dialogue-data-to';
import { Issuer } from './issuer';

/**
 * 
 * @export
 * @interface DialogueUpdateTO
 */
export interface DialogueUpdateTO {
    /**
     * 
     * @type {number}
     * @memberof DialogueUpdateTO
     */
    dialogId?: number;
    /**
     * 
     * @type {DialogueDataTO}
     * @memberof DialogueUpdateTO
     */
    dialogueDataTO?: DialogueDataTO;
    /**
     * 
     * @type {boolean}
     * @memberof DialogueUpdateTO
     */
    finished?: boolean;
    /**
     * 
     * @type {Issuer}
     * @memberof DialogueUpdateTO
     */
    requiresActionFrom?: Issuer;
}


