// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SymptomTO } from './symptom-to';

/**
 * 
 * @export
 * @interface IllnessTO
 */
export interface IllnessTO {
    /**
     * 
     * @type {number}
     * @memberof IllnessTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IllnessTO
     */
    illnessName?: string;
    /**
     * 
     * @type {Array<SymptomTO>}
     * @memberof IllnessTO
     */
    symptoms?: Array<SymptomTO>;
}


