// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject10
 */
export interface InlineObject10 {
    /**
     * the inputs that will be new intents
     * @type {Array<string>}
     * @memberof InlineObject10
     */
    intents?: Array<string>;
    /**
     * the corresponding classifier name
     * @type {string}
     * @memberof InlineObject10
     */
    classifierName?: string;
}


