// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TextClassificationPredictionRequest } from './text-classification-prediction-request';

/**
 * 
 * @export
 * @interface InlineObject14
 */
export interface InlineObject14 {
    /**
     * 
     * @type {TextClassificationPredictionRequest}
     * @memberof InlineObject14
     */
    textClassificationPredictionRequest?: TextClassificationPredictionRequest;
}


