// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IntentTO
 */
export interface IntentTO {
    /**
     * 
     * @type {number}
     * @memberof IntentTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IntentTO
     */
    intentName: string;
    /**
     * 
     * @type {number}
     * @memberof IntentTO
     */
    classifierId?: number;
    /**
     * 
     * @type {number}
     * @memberof IntentTO
     */
    numberOfSamples: number;
}


