// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TrainingType } from './training-type';

/**
 * 
 * @export
 * @interface MetricsEntity
 */
export interface MetricsEntity {
    /**
     * 
     * @type {number}
     * @memberof MetricsEntity
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsEntity
     */
    classifierId?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsEntity
     */
    intentId?: number;
    /**
     * 
     * @type {string}
     * @memberof MetricsEntity
     */
    intentName?: string;
    /**
     * 
     * @type {number}
     * @memberof MetricsEntity
     */
    precision?: number;
    /**
     * 
     * @type {TrainingType}
     * @memberof MetricsEntity
     */
    trainingType?: TrainingType;
}


