// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Seq2SeqTO
 */
export interface Seq2SeqTO {
    /**
     * 
     * @type {number}
     * @memberof Seq2SeqTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Seq2SeqTO
     */
    fileName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Seq2SeqTO
     */
    train?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Seq2SeqTO
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof Seq2SeqTO
     */
    seq2SeqName?: string;
}


