// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SlotTO } from './slot-to';

/**
 * 
 * @export
 * @interface StateTO
 */
export interface StateTO {
    /**
     * 
     * @type {number}
     * @memberof StateTO
     */
    id?: number;
    /**
     * 
     * @type {Array<SlotTO>}
     * @memberof StateTO
     */
    slots: Array<SlotTO>;
    /**
     * 
     * @type {number}
     * @memberof StateTO
     */
    dialogDataId?: number;
}


