// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TrainingStatus } from './training-status';
import { TrainingType } from './training-type';

/**
 * 
 * @export
 * @interface TrainingEntity
 */
export interface TrainingEntity {
    /**
     * 
     * @type {number}
     * @memberof TrainingEntity
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TrainingEntity
     */
    classifierId?: number;
    /**
     * 
     * @type {TrainingType}
     * @memberof TrainingEntity
     */
    trainingType?: TrainingType;
    /**
     * 
     * @type {TrainingStatus}
     * @memberof TrainingEntity
     */
    trainingStatus?: TrainingStatus;
    /**
     * 
     * @type {string}
     * @memberof TrainingEntity
     */
    startedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof TrainingEntity
     */
    answerSelectionId?: number;
}


