// tslint:disable
/**
 * Data Collection API
 * Class informations that are required for communication between the WoZ Frontend and the Backend
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AnswerSelectionEntity } from './answer-selection-entity';
import { ClassifierEntity } from './classifier-entity';
import { Seq2SeqEntity } from './seq2-seq-entity';

/**
 * 
 * @export
 * @interface UserEntity
 */
export interface UserEntity {
    /**
     * 
     * @type {number}
     * @memberof UserEntity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    password?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserEntity
     */
    enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserEntity
     */
    accountExpired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserEntity
     */
    accountLocked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserEntity
     */
    passwordExpired?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    email?: string;
    /**
     * 
     * @type {Array<ClassifierEntity>}
     * @memberof UserEntity
     */
    classifiers?: Array<ClassifierEntity>;
    /**
     * 
     * @type {Array<AnswerSelectionEntity>}
     * @memberof UserEntity
     */
    answerSelections?: Array<AnswerSelectionEntity>;
    /**
     * 
     * @type {Array<Seq2SeqEntity>}
     * @memberof UserEntity
     */
    seq2SeqEntities?: Array<Seq2SeqEntity>;
}


